services:
  - type: web
    name: cota-10
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server_v5:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIVEDOLLAR_API_KEY
        sync: false
      - key: THE_ODDS_API_KEY
        sync: false
